name = "coinect"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

# Environment variables (set via Cloudflare dashboard or wrangler secrets)
# SUPABASE_URL - Your Supabase project URL
# SUPABASE_KEY - Your Supabase anon key
